[XTrain, YTrain, XVal, YVal] = splitDataset(X, Y, 0.8);

options = trainingOptions("adam", ...
    MaxEpochs=50, ...
    MiniBatchSize=16, ...
    Shuffle="every-epoch", ...
    ValidationData={XVal, YVal}, ...
    ValidationFrequency=10, ...
    ValidationPatience=5, ...
    InitialLearnRate=1e-3, ...
    LearnRateSchedule='piecewise', ...
    LearnRateDropFactor=0.5, ...
    LearnRateDropPeriod=15, ...
    Verbose=true, ...
    Plots="training-progress");

net = trainNetwork(XTrain, YTrain, layers, options);
save redCalculadora.mat net XVal YVal